owner: thecyberplatform
repo: secretburner-status 

sites:
  - name: Secret Burner UI
    url: https://secretburner.com/
    maxResponseTime: 1000
    expectedStatusCodes:
      - 200
      - 201
  - name: Secret Burner API
    url: https://secretburner.com/api/health-check/
    maxResponseTime: 1000
    expectedStatusCodes:
      - 200

delay: 10000
skipDeleteIssues: true
assignees:
  - trentmurray

status-website:
  cname: status.secretburner.com
  logoUrl: https://secretburner.com/icons/favicon-512x512.png
  baseUrl: /
  name: Secret Burner Status
  introTitle: Real-time status and uptime monitoring for secretburner.com.
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Return to home
      href: https://secretburner.com/

# Disable auto-updates for repo description, topics, and homepage
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
